// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgHp58rzHsPyGfOnxRq_WhkyTl_0CZuuA',
    appId: '1:280018152885:android:564d8fd384dd0460147dfc',
    messagingSenderId: '280018152885',
    projectId: 'style-one-18336',
    storageBucket: 'style-one-18336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0i-UwZ7PednPXaW31N_veoqDrGVkdbw',
    appId: '1:280018152885:ios:b67e854bf2164fbc147dfc',
    messagingSenderId: '280018152885',
    projectId: 'style-one-18336',
    storageBucket: 'style-one-18336.appspot.com',
    androidClientId: '280018152885-85o25b47u4q8e4hmbe3gm6c5n7g9utq3.apps.googleusercontent.com',
    iosClientId: '280018152885-57e89odqpm6r8hkaks57531aie97c0c5.apps.googleusercontent.com',
    iosBundleId: 'com.styleone.styleOne',
  );

}